system:
  port: 10103
  name: 'im-transfer'

mysql:
  host: '${MYSQL_HOST:39.102.79.29}'
  port: '${MYSQL_PORT:3306}'
  username: '${MYSQL_USER:root}'
  password: '${MYSQL_PWD:indexlm}'
  db: '${MYSQL_DB:db_im}'
  conn:
    maxidle: 10
    maxopen: 100

redis:
  host: '${REDIS_HOST:redis.db.mytijian.cn}'
  port: '${REDIS_PORT:6379}'
  db: 6
  password: '${REDIS_PASSWORD:mytijian}'
  poolsize: 100
  cache:
    tokenexpired: 7200 # expired time 2*60*60

log:
  logPath: '/opt'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

jwt:
  signKey: 'index'
  expires: 36000
nacos:
  ipAddr: "127.0.0.1"
  port: 8848
  namespaceId: "develop"
