system:
  port: 10101
  name: 'im-api'

redis:
  host: '${REDIS_HOST:redis.db.mytijian.cn}'
  port: '${REDIS_PORT:6379}'
  db: 6
  password: '${REDIS_PASSWORD:mytijian}'
  poolsize: 100
  cache:
    tokenexpired: 7200 # expired time 2*60*60

log:
  level: 'info'
  file: 'C:/namespace/logs'

jwt:
  signKey: 'index'
  expires: 36000

nacos:
  ipAddr: "127.0.0.1"
  port: 8848
  namespaceId: "develop"